### ISSUE TITLE
Predict error

### ISSUE THREAD

**Issue by emorysaba** [janclemenslab/das#10] opened 2021-07-08 21:54 UTC
Hello! I'm running into an issue with the predict function (screenshot attached below) - I've tried re-assembling datasets and re-training models every which way and still run into this issue about 2/3rds of the time when using it. Any idea as to what could be causing this? Thank you in advance!
<img width="811" alt="Screen Shot 2021-07-08 at 5 53 18 PM" src="https://user-images.githubusercontent.com/43159725/124995435-62b69500-e015-11eb-8b88-1b0ced183dcf.png">

**Comment by postpop** [comment] 2021-07-09 08:34
Hi,

thank you for raising this issue! We pad the signal to fill batches at the end of the signal - this can lead to cases where there are detections that extend beyond the original signal. I will add a check that prevents that from happening and will let you know once that is fixed.

**Comment by postpop** [comment] 2021-07-09 08:50
I pushed a potential fix to the GUI repo (new v0.26.1 of xarray-behave). Can you update with `pip install xarray-behave --upgrade` and let me know whether this fixes the issue? Thanks!

**Comment by emorysaba** [comment] 2021-07-09 16:02
I downloaded the new version from the GitHub page and unfortunately, there seems to be a new error - now whenever I load any audio file, this pops up
<img width="565" alt="Screen Shot 2021-07-09 at 12 01 27 PM" src="https://user-images.githubusercontent.com/43159725/125106290-7b728980-e0ad-11eb-88e5-122b3d043bf9.png">

**Comment by emorysaba** [comment] 2021-07-09 16:04
These are the errors when opening the file and running predict, respectively in full
<img width="956" alt="Screen Shot 2021-07-09 at 12 03 55 PM" src="https://user-images.githubusercontent.com/43159725/125106628-d6a47c00-e0ad-11eb-9092-dddd533ea93f.png">
<img width="986" alt="Screen Shot 2021-07-09 at 12 04 02 PM" src="https://user-images.githubusercontent.com/43159725/125106630-d73d1280-e0ad-11eb-90f5-8ea276b0a977.png">

**Comment by postpop** [comment] 2021-07-09 16:56
I've pushed a new version that should fix the predict issue. 
Please upgrade the GUI with `pip install xarray-behave --upgrade`
and let me know whether this helps.

The other error is independent - I've opened a new issue #11. Looks like some issue caused by a new version of pyqtgraph or qt. Could you post the output of `conda list` there? Sorry about the hassle...

**Comment by emorysaba** [comment] 2021-07-12 17:57
Hi! The original problem seems to be fixed, but now when I run predict, the model finds 1 or no segments where it used to accurately predict many.

**Comment by postpop** [comment] 2021-07-12 18:46
I messed this up, terribly sorry about that. I've pushed code that fixes the issue now. Hopefully...
Please update das via `pip install das --upgrade` and let me know whether all works as expected now.
Thanks for your help and your patience!

**Comment by emorysaba** [comment] 2021-07-12 18:58
Yes, it seems to be working as expected - thank you for all your help, I really do appreciate it!

**Comment by postpop** [comment] 2021-07-12 19:02
Great - closing this.

**Closed by postpop** 2021-07-12 19:02 UTC
